'use strict';

/**
 * Bundles the published lib (dist/index.js, CommonJS) into a browser-friendly
 * IIFE bundle that the demo HTML can load via a regular <script> tag.
 *
 * Output: demo/react-fusion-state.umd.js
 *   - Global name: ReactFusionState
 *   - React / React-DOM are NOT bundled — they are mapped to window.React /
 *     window.ReactDOM (loaded from a CDN by the demo HTML), mirroring the
 *     real `peerDependencies` contract.
 *
 * This script is run automatically by `npm run build`. To rebuild manually:
 *     node scripts/build-demo.js
 */

const path = require('path');
const fs = require('fs');
const esbuild = require('esbuild');

const root = path.resolve(__dirname, '..');
const entry = path.join(root, 'dist', 'index.js');
const outfile = path.join(root, 'demo', 'react-fusion-state.umd.js');

if (!fs.existsSync(entry)) {
  console.error(
    '[build-demo] dist/index.js not found. Run `tsc -p tsconfig-build.json` first.',
  );
  process.exit(1);
}

// Read the package version so the demo can display it under the title without
// drifting from package.json.
const pkg = JSON.parse(
  fs.readFileSync(path.join(root, 'package.json'), 'utf8'),
);
const version = pkg.version;

/**
 * esbuild plugin: rewrite imports of `react` and `react-dom` to read from
 * browser globals (`window.React`, `window.ReactDOM`). Lets the demo bundle
 * stay tiny and keeps React loaded from a CDN like a real consumer would.
 */
const browserGlobalsPlugin = {
  name: 'browser-globals',
  setup(build) {
    const globals = {react: 'React', 'react-dom': 'ReactDOM'};
    build.onResolve({filter: /^(react|react-dom)$/}, args => ({
      path: args.path,
      namespace: 'browser-globals',
    }));
    build.onLoad({filter: /.*/, namespace: 'browser-globals'}, args => ({
      contents: `module.exports = (typeof window !== 'undefined' ? window : globalThis).${globals[args.path]};`,
      loader: 'js',
    }));
  },
};

esbuild
  .build({
    entryPoints: [entry],
    bundle: true,
    format: 'iife',
    globalName: 'ReactFusionState',
    platform: 'browser',
    target: 'es2019',
    outfile,
    plugins: [browserGlobalsPlugin],
    legalComments: 'none',
    banner: {
      js:
        '/* react-fusion-state demo bundle — auto-generated by scripts/build-demo.js. ' +
        'Do not edit by hand. Regenerate with `npm run build` (or `npm run build:demo`). */',
    },
    // Append a tiny footer that exposes the package version on the global,
    // so the demo HTML can render `Version v{ReactFusionState.VERSION}` without
    // hardcoding the number.
    footer: {
      js: `ReactFusionState.VERSION = ${JSON.stringify(version)};`,
    },
    logLevel: 'info',
  })
  .then(() => {
    const stat = fs.statSync(outfile);
    const kb = (stat.size / 1024).toFixed(2);
    console.log(`[build-demo] wrote ${path.relative(root, outfile)} (${kb} KB)`);
  })
  .catch(err => {
    console.error('[build-demo] esbuild failed:', err);
    process.exit(1);
  });
