/* react-fusion-state demo bundle — auto-generated by scripts/build-demo.js. Do not edit by hand. Regenerate with `npm run build` (or `npm run build:demo`). */
"use strict";
var ReactFusionState = (() => {
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
    get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
  }) : x)(function(x) {
    if (typeof require !== "undefined") return require.apply(this, arguments);
    throw Error('Dynamic require of "' + x + '" is not supported');
  });
  var __commonJS = (cb, mod) => function __require2() {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  };

  // browser-globals:react
  var require_react = __commonJS({
    "browser-globals:react"(exports, module) {
      module.exports = (typeof window !== "undefined" ? window : globalThis).React;
    }
  });

  // dist/types.js
  var require_types = __commonJS({
    "dist/types.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.PersistenceError = exports.FusionStateError = exports.FusionStateErrorMessages = void 0;
      var FusionStateErrorMessages;
      (function(FusionStateErrorMessages2) {
        FusionStateErrorMessages2["PROVIDER_MISSING"] = "ReactFusionState Error: useFusionState must be used within a FusionStateProvider";
        FusionStateErrorMessages2["KEY_ALREADY_INITIALIZING"] = `ReactFusionState Error: Key "{0}" is already being initialized. Consider checking if the key is being initialized elsewhere or if there's a logic error.`;
        FusionStateErrorMessages2["KEY_MISSING_NO_INITIAL"] = 'ReactFusionState Error: Key "{0}" does not exist and no initial value provided. Ensure the key is initialized with a value before use.';
        FusionStateErrorMessages2["PERSISTENCE_READ_ERROR"] = "ReactFusionState Error: Failed to read state from storage: {0}";
        FusionStateErrorMessages2["PERSISTENCE_WRITE_ERROR"] = "ReactFusionState Error: Failed to write state to storage: {0}";
        FusionStateErrorMessages2["STORAGE_ADAPTER_MISSING"] = "ReactFusionState Error: Storage adapter is required for persistence configuration";
      })(FusionStateErrorMessages = exports.FusionStateErrorMessages || (exports.FusionStateErrorMessages = {}));
      var FusionStateError = class extends Error {
        constructor(code, message, context) {
          super(message);
          this.code = code;
          this.context = context;
          this.name = "FusionStateError";
        }
      };
      exports.FusionStateError = FusionStateError;
      var PersistenceError = class extends FusionStateError {
        constructor(message, operation, storageKey, context) {
          super(operation === "read" ? "PERSISTENCE_READ_ERROR" : "PERSISTENCE_WRITE_ERROR", message, context);
          this.operation = operation;
          this.storageKey = storageKey;
          this.name = "PersistenceError";
        }
      };
      exports.PersistenceError = PersistenceError;
    }
  });

  // dist/storage/storageAdapters.js
  var require_storageAdapters = __commonJS({
    "dist/storage/storageAdapters.js"(exports) {
      "use strict";
      var __awaiter = exports && exports.__awaiter || function(thisArg, _arguments, P, generator) {
        function adopt(value) {
          return value instanceof P ? value : new P(function(resolve) {
            resolve(value);
          });
        }
        return new (P || (P = Promise))(function(resolve, reject) {
          function fulfilled(value) {
            try {
              step(generator.next(value));
            } catch (e) {
              reject(e);
            }
          }
          function rejected(value) {
            try {
              step(generator["throw"](value));
            } catch (e) {
              reject(e);
            }
          }
          function step(result) {
            result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected);
          }
          step((generator = generator.apply(thisArg, _arguments || [])).next());
        });
      };
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.NoopStorageAdapter = exports.createLocalStorageAdapter = exports.createNoopStorageAdapter = void 0;
      var createNoopStorageAdapter = () => ({
        getItem(key) {
          return __awaiter(this, void 0, void 0, function* () {
            return null;
          });
        },
        setItem(key, value) {
          return __awaiter(this, void 0, void 0, function* () {
          });
        },
        removeItem(key) {
          return __awaiter(this, void 0, void 0, function* () {
          });
        }
      });
      exports.createNoopStorageAdapter = createNoopStorageAdapter;
      var createLocalStorageAdapter = (debug = false) => {
        if (typeof localStorage === "undefined") {
          if (debug) {
            console.warn("localStorage is not available, falling back to noop adapter");
          }
          return (0, exports.createNoopStorageAdapter)();
        }
        return {
          getItem(key) {
            return __awaiter(this, void 0, void 0, function* () {
              try {
                return localStorage.getItem(key);
              } catch (error) {
                if (debug) {
                  console.error("Error reading from localStorage:", error);
                }
                return null;
              }
            });
          },
          getItemSync(key) {
            try {
              return localStorage.getItem(key);
            } catch (error) {
              if (debug) {
                console.error("Error reading from localStorage:", error);
              }
              return null;
            }
          },
          setItem(key, value) {
            return __awaiter(this, void 0, void 0, function* () {
              try {
                localStorage.setItem(key, value);
              } catch (error) {
                if (debug) {
                  console.error("Error writing to localStorage:", error);
                }
              }
            });
          },
          removeItem(key) {
            return __awaiter(this, void 0, void 0, function* () {
              try {
                localStorage.removeItem(key);
              } catch (error) {
                if (debug) {
                  console.error("Error removing from localStorage:", error);
                }
              }
            });
          }
        };
      };
      exports.createLocalStorageAdapter = createLocalStorageAdapter;
      exports.NoopStorageAdapter = exports.createNoopStorageAdapter;
    }
  });

  // dist/storage/asyncStorageAdapter.js
  var require_asyncStorageAdapter = __commonJS({
    "dist/storage/asyncStorageAdapter.js"(exports) {
      "use strict";
      var __awaiter = exports && exports.__awaiter || function(thisArg, _arguments, P, generator) {
        function adopt(value) {
          return value instanceof P ? value : new P(function(resolve) {
            resolve(value);
          });
        }
        return new (P || (P = Promise))(function(resolve, reject) {
          function fulfilled(value) {
            try {
              step(generator.next(value));
            } catch (e) {
              reject(e);
            }
          }
          function rejected(value) {
            try {
              step(generator["throw"](value));
            } catch (e) {
              reject(e);
            }
          }
          function step(result) {
            result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected);
          }
          step((generator = generator.apply(thisArg, _arguments || [])).next());
        });
      };
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.createAsyncStorageAdapter = void 0;
      function createAsyncStorageAdapter(AsyncStorage, debug = false) {
        return {
          getItem(key) {
            return __awaiter(this, void 0, void 0, function* () {
              try {
                return yield AsyncStorage.getItem(key);
              } catch (error) {
                if (debug) {
                  console.error("Error reading from AsyncStorage:", error);
                }
                return null;
              }
            });
          },
          setItem(key, value) {
            return __awaiter(this, void 0, void 0, function* () {
              try {
                yield AsyncStorage.setItem(key, value);
              } catch (error) {
                if (debug) {
                  console.error("Error writing to AsyncStorage:", error);
                }
              }
            });
          },
          removeItem(key) {
            return __awaiter(this, void 0, void 0, function* () {
              try {
                yield AsyncStorage.removeItem(key);
              } catch (error) {
                if (debug) {
                  console.error("Error removing from AsyncStorage:", error);
                }
              }
            });
          }
        };
      }
      exports.createAsyncStorageAdapter = createAsyncStorageAdapter;
    }
  });

  // dist/storage/autoDetect.js
  var require_autoDetect = __commonJS({
    "dist/storage/autoDetect.js"(exports) {
      "use strict";
      var __awaiter = exports && exports.__awaiter || function(thisArg, _arguments, P, generator) {
        function adopt(value) {
          return value instanceof P ? value : new P(function(resolve) {
            resolve(value);
          });
        }
        return new (P || (P = Promise))(function(resolve, reject) {
          function fulfilled(value) {
            try {
              step(generator.next(value));
            } catch (e) {
              reject(e);
            }
          }
          function rejected(value) {
            try {
              step(generator["throw"](value));
            } catch (e) {
              reject(e);
            }
          }
          function step(result) {
            result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected);
          }
          step((generator = generator.apply(thisArg, _arguments || [])).next());
        });
      };
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.createMemoryStorageAdapter = exports.detectBestStorageAdapter = exports.isSSREnvironment = void 0;
      var storageAdapters_1 = require_storageAdapters();
      var asyncStorageAdapter_1 = require_asyncStorageAdapter();
      function isSSREnvironment() {
        if (typeof navigator !== "undefined" && navigator.product === "ReactNative") {
          return false;
        }
        return typeof window === "undefined";
      }
      exports.isSSREnvironment = isSSREnvironment;
      var cachedAdapter = null;
      function detectBestStorageAdapter(debug = false) {
        if (cachedAdapter)
          return cachedAdapter;
        cachedAdapter = resolveAdapter(debug);
        return cachedAdapter;
      }
      exports.detectBestStorageAdapter = detectBestStorageAdapter;
      function resolveAdapter(debug) {
        if (isSSREnvironment()) {
          if (debug) {
            console.info("[FusionState] SSR environment detected, using memory-only mode.");
          }
          return (0, storageAdapters_1.createNoopStorageAdapter)();
        }
        if (isReactNativeEnvironment()) {
          try {
            const req = Function('try { return typeof require !== "undefined" && require; } catch(_) { return undefined; }')();
            const modName = "@react-native-async-storage/async-storage";
            const AsyncStorage = req ? req(modName) : void 0;
            if (AsyncStorage) {
              if (debug) {
                console.info("[FusionState] Using AsyncStorage adapter (auto-detected).");
              }
              const asImpl = AsyncStorage.default || AsyncStorage;
              return (0, asyncStorageAdapter_1.createAsyncStorageAdapter)(asImpl, debug);
            }
            if (debug) {
              console.info("[FusionState] React Native detected but AsyncStorage not found. Falling back to memory adapter. ");
            }
          } catch (e) {
            if (debug) {
              console.warn("[FusionState] Failed to load AsyncStorage adapter:", e);
            }
          }
          return (0, storageAdapters_1.createNoopStorageAdapter)();
        }
        if (isWebEnvironment()) {
          try {
            window.localStorage.setItem("fusion_test", "test");
            window.localStorage.removeItem("fusion_test");
            return (0, storageAdapters_1.createLocalStorageAdapter)(debug);
          } catch (e) {
            if (debug) {
              console.warn("[FusionState] localStorage detected but not available:", e);
            }
          }
        }
        if (debug) {
          console.info("[FusionState] No storage detected, using memory-only mode.");
        }
        return (0, storageAdapters_1.createNoopStorageAdapter)();
      }
      function isReactNativeEnvironment() {
        if (typeof navigator !== "undefined" && navigator.product === "ReactNative") {
          return true;
        }
        if (typeof global !== "undefined" && typeof window === "undefined") {
          return true;
        }
        if (typeof global !== "undefined" && // @ts-ignore - Runtime check
        (global.__fbBatchedBridge || global.nativeCallSyncHook)) {
          return true;
        }
        return false;
      }
      function isWebEnvironment() {
        try {
          return typeof window !== "undefined" && typeof window.localStorage !== "undefined";
        } catch (_a) {
          return false;
        }
      }
      function createMemoryStorageAdapter() {
        const storage = /* @__PURE__ */ new Map();
        return {
          getItem(key) {
            return __awaiter(this, void 0, void 0, function* () {
              return storage.has(key) ? storage.get(key) : null;
            });
          },
          setItem(key, value) {
            return __awaiter(this, void 0, void 0, function* () {
              storage.set(key, value);
            });
          },
          removeItem(key) {
            return __awaiter(this, void 0, void 0, function* () {
              storage.delete(key);
            });
          }
        };
      }
      exports.createMemoryStorageAdapter = createMemoryStorageAdapter;
    }
  });

  // dist/utils/index.js
  var require_utils = __commonJS({
    "dist/utils/index.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.simpleDeepEqual = exports.shallowEqual = exports.customIsEqual = exports.debounce = exports.formatErrorMessage = void 0;
      var formatErrorMessage = (message, ...values) => {
        return values.reduce((msg, value, index) => msg.replace(`{${index}}`, value), message);
      };
      exports.formatErrorMessage = formatErrorMessage;
      function debounce(fn, delay) {
        let timer = null;
        return (...args) => {
          if (timer)
            clearTimeout(timer);
          timer = setTimeout(() => fn(...args), delay);
        };
      }
      exports.debounce = debounce;
      var customIsEqual = (a, b) => {
        if (a === b)
          return true;
        if (a == null || b == null)
          return a === b;
        if (typeof a !== typeof b)
          return false;
        if (typeof a !== "object")
          return false;
        if (Array.isArray(a)) {
          if (!Array.isArray(b) || a.length !== b.length)
            return false;
          for (let i = 0; i < a.length; i++) {
            if (!(0, exports.customIsEqual)(a[i], b[i]))
              return false;
          }
          return true;
        }
        if (Array.isArray(b))
          return false;
        const keysA = Object.keys(a);
        const keysB = Object.keys(b);
        if (keysA.length !== keysB.length)
          return false;
        for (const key of keysA) {
          if (!keysB.includes(key))
            return false;
          if (!(0, exports.customIsEqual)(a[key], b[key]))
            return false;
        }
        return true;
      };
      exports.customIsEqual = customIsEqual;
      var shallowEqual = (a, b) => {
        if (a === b)
          return true;
        if (a == null || b == null)
          return a === b;
        if (typeof a !== typeof b)
          return false;
        if (typeof a !== "object")
          return false;
        if (Array.isArray(a)) {
          if (!Array.isArray(b) || a.length !== b.length)
            return false;
          for (let i = 0; i < a.length; i++) {
            if (a[i] !== b[i])
              return false;
          }
          return true;
        }
        if (Array.isArray(b))
          return false;
        const keysA = Object.keys(a);
        const keysB = Object.keys(b);
        if (keysA.length !== keysB.length)
          return false;
        for (const key of keysA) {
          if (!keysB.includes(key) || a[key] !== b[key]) {
            return false;
          }
        }
        return true;
      };
      exports.shallowEqual = shallowEqual;
      exports.simpleDeepEqual = exports.customIsEqual;
    }
  });

  // dist/devtools.js
  var require_devtools = __commonJS({
    "dist/devtools.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.DevToolsActions = exports.useDevTools = exports.getDevTools = exports.createDevTools = void 0;
      var FusionStateDevTools = class {
        constructor(config = {}) {
          var _a, _b;
          this.devtools = null;
          this.isEnabled = false;
          this.actionCounter = 0;
          this.config = {
            name: config.name || "FusionState",
            trace: (_a = config.trace) !== null && _a !== void 0 ? _a : true,
            maxAge: config.maxAge || 50,
            devOnly: (_b = config.devOnly) !== null && _b !== void 0 ? _b : true
          };
          this.initialize();
        }
        initialize() {
          if (this.config.devOnly && false) {
            return;
          }
          if (typeof window !== "undefined" && window.__REDUX_DEVTOOLS_EXTENSION__) {
            try {
              this.devtools = window.__REDUX_DEVTOOLS_EXTENSION__.connect({
                name: this.config.name,
                trace: this.config.trace,
                maxAge: this.config.maxAge,
                features: {
                  pause: true,
                  lock: true,
                  persist: true,
                  export: true,
                  import: "custom",
                  jump: true,
                  skip: true,
                  reorder: true,
                  dispatch: true,
                  test: true
                }
              });
              this.isEnabled = true;
              this.devtools.subscribe((message) => {
                this.handleDevToolsMessage(message);
              });
            } catch (error) {
              console.warn("[FusionState DevTools] Failed to connect:", error);
            }
          }
        }
        handleDevToolsMessage(message) {
          var _a, _b;
          switch (message.type) {
            case "DISPATCH":
              switch ((_a = message.payload) === null || _a === void 0 ? void 0 : _a.type) {
                case "JUMP_TO_ACTION":
                case "JUMP_TO_STATE":
                  (_b = this.onTimeTravel) === null || _b === void 0 ? void 0 : _b.call(this, message.payload);
                  break;
              }
              break;
          }
        }
        init(state) {
          if (!this.isEnabled || !this.devtools)
            return;
          try {
            this.devtools.init(state);
          } catch (error) {
            console.warn("[FusionState DevTools] Init failed:", error);
          }
        }
        send(actionType, state, key, payload) {
          if (!this.isEnabled || !this.devtools)
            return;
          try {
            const action = {
              type: `${actionType}${key ? ` (${key})` : ""}`,
              key,
              payload,
              timestamp: Date.now()
            };
            this.devtools.send(action, state);
            this.actionCounter++;
          } catch (error) {
            console.warn("[FusionState DevTools] Send failed:", error);
          }
        }
        /** Check if DevTools are active */
        get enabled() {
          return this.isEnabled;
        }
        /** Obtenir les statistiques */
        get stats() {
          return {
            enabled: this.isEnabled,
            actionCount: this.actionCounter,
            config: this.config
          };
        }
      };
      var devToolsInstance = null;
      function createDevTools(config) {
        if (!devToolsInstance) {
          devToolsInstance = new FusionStateDevTools(config);
        }
        return devToolsInstance;
      }
      exports.createDevTools = createDevTools;
      function getDevTools() {
        return devToolsInstance;
      }
      exports.getDevTools = getDevTools;
      function useDevTools() {
        var _a, _b, _c;
        const devtools = getDevTools();
        return {
          enabled: (_a = devtools === null || devtools === void 0 ? void 0 : devtools.enabled) !== null && _a !== void 0 ? _a : false,
          stats: (_b = devtools === null || devtools === void 0 ? void 0 : devtools.stats) !== null && _b !== void 0 ? _b : null,
          send: (_c = devtools === null || devtools === void 0 ? void 0 : devtools.send.bind(devtools)) !== null && _c !== void 0 ? _c : (() => {
          })
        };
      }
      exports.useDevTools = useDevTools;
      exports.DevToolsActions = {
        INIT: "INIT",
        SET_STATE: "SET_STATE",
        UPDATE_KEY: "UPDATE_KEY",
        PERSIST_LOAD: "PERSIST_LOAD",
        PERSIST_SAVE: "PERSIST_SAVE",
        ERROR: "ERROR"
      };
    }
  });

  // dist/utils/batch.js
  var require_batch = __commonJS({
    "dist/utils/batch.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.batch = void 0;
      var resolved = null;
      function resolve() {
        if (resolved)
          return resolved;
        const safeRequire = typeof __require !== "undefined" ? (name) => {
          try {
            return __require(name);
          } catch (_a) {
            return void 0;
          }
        } : null;
        if (safeRequire) {
          const ReactDOM = safeRequire("react-dom");
          if (ReactDOM && ReactDOM.unstable_batchedUpdates) {
            return resolved = ReactDOM.unstable_batchedUpdates;
          }
          const ReactNative = safeRequire("react-native");
          if (ReactNative && ReactNative.unstable_batchedUpdates) {
            return resolved = ReactNative.unstable_batchedUpdates;
          }
        }
        return resolved = (fn) => fn();
      }
      var batch = (fn) => resolve()(fn);
      exports.batch = batch;
    }
  });

  // dist/FusionStateProvider.js
  var require_FusionStateProvider = __commonJS({
    "dist/FusionStateProvider.js"(exports) {
      "use strict";
      var __createBinding = exports && exports.__createBinding || (Object.create ? (function(o, m, k, k2) {
        if (k2 === void 0) k2 = k;
        var desc = Object.getOwnPropertyDescriptor(m, k);
        if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
          desc = { enumerable: true, get: function() {
            return m[k];
          } };
        }
        Object.defineProperty(o, k2, desc);
      }) : (function(o, m, k, k2) {
        if (k2 === void 0) k2 = k;
        o[k2] = m[k];
      }));
      var __setModuleDefault = exports && exports.__setModuleDefault || (Object.create ? (function(o, v) {
        Object.defineProperty(o, "default", { enumerable: true, value: v });
      }) : function(o, v) {
        o["default"] = v;
      });
      var __importStar = exports && exports.__importStar || function(mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) {
          for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
        }
        __setModuleDefault(result, mod);
        return result;
      };
      var __awaiter = exports && exports.__awaiter || function(thisArg, _arguments, P, generator) {
        function adopt(value) {
          return value instanceof P ? value : new P(function(resolve) {
            resolve(value);
          });
        }
        return new (P || (P = Promise))(function(resolve, reject) {
          function fulfilled(value) {
            try {
              step(generator.next(value));
            } catch (e) {
              reject(e);
            }
          }
          function rejected(value) {
            try {
              step(generator["throw"](value));
            } catch (e) {
              reject(e);
            }
          }
          function step(result) {
            result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected);
          }
          step((generator = generator.apply(thisArg, _arguments || [])).next());
        });
      };
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.FusionStateProvider = exports.useGlobalState = void 0;
      var react_1 = __importStar(require_react());
      var types_1 = require_types();
      var storageAdapters_1 = require_storageAdapters();
      var autoDetect_1 = require_autoDetect();
      var utils_1 = require_utils();
      var devtools_1 = require_devtools();
      var batch_1 = require_batch();
      var GlobalStateContext = (0, react_1.createContext)(void 0);
      var useGlobalState = () => {
        const context = (0, react_1.useContext)(GlobalStateContext);
        if (!context) {
          throw new Error(types_1.FusionStateErrorMessages.PROVIDER_MISSING);
        }
        return context;
      };
      exports.useGlobalState = useGlobalState;
      function normalizePersistenceConfig(config, debug = false) {
        if (!config)
          return void 0;
        const defaultAdapter = (0, autoDetect_1.detectBestStorageAdapter)(debug);
        if (typeof config === "boolean") {
          return {
            adapter: defaultAdapter,
            persistKeys: config ? true : false,
            loadOnInit: true,
            saveOnChange: true
          };
        }
        if (Array.isArray(config)) {
          return {
            adapter: defaultAdapter,
            persistKeys: config,
            loadOnInit: true,
            saveOnChange: true
          };
        }
        if ("adapter" in config) {
          return config;
        }
        const simple = config;
        return {
          adapter: simple.adapter || defaultAdapter,
          persistKeys: simple.persistKeys || false,
          debounceTime: simple.debounce,
          loadOnInit: true,
          saveOnChange: true,
          onLoadError: simple.onLoadError,
          onSaveError: simple.onSaveError
        };
      }
      exports.FusionStateProvider = (0, react_1.memo)(({ children, initialState = {}, debug = false, persistence, devTools = false }) => {
        var _a, _b, _c, _d, _e, _f;
        const normalizedPersistence = (0, react_1.useMemo)(() => normalizePersistenceConfig(persistence, debug), [persistence, debug]);
        const devToolsInstance = (0, react_1.useMemo)(() => {
          var _a2;
          if (!devTools)
            return null;
          const config = typeof devTools === "boolean" ? { name: "FusionState", devOnly: true } : Object.assign(Object.assign({}, devTools), { devOnly: (_a2 = devTools.devOnly) !== null && _a2 !== void 0 ? _a2 : true });
          return (0, devtools_1.createDevTools)(config);
        }, [devTools]);
        const persistenceRef = (0, react_1.useRef)(normalizedPersistence);
        const storageAdapter = (0, react_1.useMemo)(() => {
          var _a2;
          return ((_a2 = persistenceRef.current) === null || _a2 === void 0 ? void 0 : _a2.adapter) || (0, storageAdapters_1.createNoopStorageAdapter)();
        }, []);
        const keyPrefix = "fusion_state";
        const shouldLoadOnInit = (_b = (_a = persistenceRef.current) === null || _a === void 0 ? void 0 : _a.loadOnInit) !== null && _b !== void 0 ? _b : true;
        const shouldSaveOnChange = (_d = (_c = persistenceRef.current) === null || _c === void 0 ? void 0 : _c.saveOnChange) !== null && _d !== void 0 ? _d : true;
        const debounceTime = (_f = (_e = persistenceRef.current) === null || _e === void 0 ? void 0 : _e.debounceTime) !== null && _f !== void 0 ? _f : 0;
        const syncLoadErrorRef = (0, react_1.useRef)(null);
        const [state, setStateRaw] = (0, react_1.useState)(() => {
          if (shouldLoadOnInit && storageAdapter && typeof window !== "undefined") {
            try {
              const extendedAdapter = storageAdapter;
              if (extendedAdapter.getItemSync) {
                const item = extendedAdapter.getItemSync(`${keyPrefix}_all`);
                if (item) {
                  const storedData = JSON.parse(item);
                  if (debug) {
                    console.log("[FusionState] Loaded state synchronously:", storedData);
                  }
                  return Object.assign(Object.assign({}, initialState), storedData);
                }
              }
            } catch (error) {
              const errorObj = error instanceof Error ? error : new Error(String(error));
              syncLoadErrorRef.current = errorObj;
              if (debug) {
                console.warn("[FusionState] Synchronous load failed, will try async:", error);
              }
            }
          }
          return initialState;
        });
        const computeInitialHydrated = () => {
          if (!persistenceRef.current)
            return true;
          if (!shouldLoadOnInit || !storageAdapter)
            return true;
          if (typeof window !== "undefined") {
            const extendedAdapter = storageAdapter;
            if (extendedAdapter.getItemSync)
              return true;
          }
          return false;
        };
        const [isHydrated, setIsHydrated] = (0, react_1.useState)(computeInitialHydrated);
        const isHydratedRef = (0, react_1.useRef)(isHydrated);
        (0, react_1.useEffect)(() => {
          if (devToolsInstance === null || devToolsInstance === void 0 ? void 0 : devToolsInstance.enabled) {
            devToolsInstance.init(state);
            devToolsInstance.send(devtools_1.DevToolsActions.INIT, state, void 0, {
              initialState
            });
          }
        }, [devToolsInstance]);
        const initializingKeys = (0, react_1.useRef)(/* @__PURE__ */ new Set());
        const isInitialLoadDone = (0, react_1.useRef)(false);
        const prevPersistedState = (0, react_1.useRef)({});
        const prevStateRef = (0, react_1.useRef)(state);
        const skipPersistOnceRef = (0, react_1.useRef)(false);
        (0, react_1.useEffect)(() => {
          if (syncLoadErrorRef.current) {
            if (debug) {
              console.error((0, utils_1.formatErrorMessage)(types_1.FusionStateErrorMessages.PERSISTENCE_READ_ERROR, String(syncLoadErrorRef.current)));
            }
            const config = persistenceRef.current;
            if (config === null || config === void 0 ? void 0 : config.onLoadError) {
              config.onLoadError(syncLoadErrorRef.current, `${keyPrefix}_all`);
            }
            syncLoadErrorRef.current = null;
          }
        }, []);
        (0, react_1.useEffect)(() => {
          const markHydrated = () => {
            isInitialLoadDone.current = true;
            if (!isHydratedRef.current) {
              isHydratedRef.current = true;
              setIsHydrated(true);
            }
          };
          if (shouldLoadOnInit && !isInitialLoadDone.current && storageAdapter) {
            const loadStateFromStorage = () => __awaiter(void 0, void 0, void 0, function* () {
              try {
                const storedDataRaw = yield storageAdapter.getItem(`${keyPrefix}_all`);
                if (storedDataRaw) {
                  const storedData = JSON.parse(storedDataRaw);
                  prevPersistedState.current = Object.assign({}, storedData);
                  skipPersistOnceRef.current = true;
                  setStateRaw((prevState) => {
                    const mergedState = Object.assign(Object.assign({}, prevState), storedData);
                    if (debug) {
                      console.log("[FusionState] Loaded state from storage (async):", storedData);
                      console.log("[FusionState] Merged state:", mergedState);
                    }
                    return mergedState;
                  });
                }
                markHydrated();
                if (debug && !storedDataRaw) {
                  console.log("[FusionState] No stored data found");
                }
              } catch (error) {
                const errorObj = error instanceof Error ? error : new Error(String(error));
                if (debug) {
                  console.error((0, utils_1.formatErrorMessage)(types_1.FusionStateErrorMessages.PERSISTENCE_READ_ERROR, String(error)));
                }
                const config = persistenceRef.current;
                if (config === null || config === void 0 ? void 0 : config.onLoadError) {
                  config.onLoadError(errorObj, `${keyPrefix}_all`);
                }
                markHydrated();
              }
            });
            loadStateFromStorage();
          } else {
            isInitialLoadDone.current = true;
          }
        }, [storageAdapter, keyPrefix, shouldLoadOnInit, debug]);
        const filterPersistKeys = (0, react_1.useMemo)(() => {
          return (newState) => {
            var _a2;
            const persistKeys = (_a2 = persistenceRef.current) === null || _a2 === void 0 ? void 0 : _a2.persistKeys;
            if (!persistKeys)
              return {};
            if (persistKeys === true)
              return Object.assign({}, newState);
            const filteredState = {};
            if (Array.isArray(persistKeys)) {
              persistKeys.forEach((key) => {
                if (key in newState) {
                  filteredState[key] = newState[key];
                }
              });
            } else if (typeof persistKeys === "function") {
              Object.keys(newState).forEach((key) => {
                const filterFn = persistKeys;
                if (filterFn(key, newState[key])) {
                  filteredState[key] = newState[key];
                }
              });
            }
            return filteredState;
          };
        }, []);
        const saveStateToStorage = (0, react_1.useMemo)(() => {
          const save = (newState) => __awaiter(void 0, void 0, void 0, function* () {
            if (!storageAdapter || !shouldSaveOnChange)
              return;
            const stateToSave = filterPersistKeys(newState);
            if (Object.keys(stateToSave).length === 0)
              return;
            try {
              const hasChanged = !(0, utils_1.simpleDeepEqual)(stateToSave, prevPersistedState.current);
              if (!hasChanged) {
                if (debug) {
                  console.log("[FusionState] No changes detected, skipping save");
                }
                return;
              }
              const persistenceConfig = persistenceRef.current;
              if (persistenceConfig) {
                const customSaveCallback = "customSaveCallback" in persistenceConfig ? persistenceConfig.customSaveCallback : void 0;
                if (customSaveCallback && typeof customSaveCallback === "function") {
                  yield customSaveCallback(stateToSave, storageAdapter, keyPrefix);
                } else {
                  yield storageAdapter.setItem(`${keyPrefix}_all`, JSON.stringify(stateToSave));
                }
              } else {
                yield storageAdapter.setItem(`${keyPrefix}_all`, JSON.stringify(stateToSave));
              }
              prevPersistedState.current = Object.assign({}, stateToSave);
              if (debug) {
                console.log("[FusionState] Saved state to storage:", stateToSave);
              }
            } catch (error) {
              const errorObj = error instanceof Error ? error : new Error(String(error));
              if (debug) {
                console.error((0, utils_1.formatErrorMessage)(types_1.FusionStateErrorMessages.PERSISTENCE_WRITE_ERROR, String(error)));
              }
              const config = persistenceRef.current;
              if (config === null || config === void 0 ? void 0 : config.onSaveError) {
                config.onSaveError(errorObj, stateToSave);
              }
            }
          });
          return debounceTime > 0 ? (0, utils_1.debounce)(save, debounceTime) : save;
        }, [
          storageAdapter,
          keyPrefix,
          shouldSaveOnChange,
          debug,
          debounceTime,
          filterPersistKeys
        ]);
        const keyListenersRef = (0, react_1.useRef)(/* @__PURE__ */ new Map());
        const subscribeKey = (0, react_1.useCallback)((key, listener) => {
          let set = keyListenersRef.current.get(key);
          if (!set) {
            set = /* @__PURE__ */ new Set();
            keyListenersRef.current.set(key, set);
          }
          set.add(listener);
          return () => {
            set.delete(listener);
            if (set.size === 0) {
              keyListenersRef.current.delete(key);
            }
          };
        }, []);
        const notifyKey = (0, react_1.useCallback)((key) => {
          const listeners = keyListenersRef.current.get(key);
          if (listeners) {
            (0, batch_1.batch)(() => {
              listeners.forEach((l) => l());
            });
          }
        }, []);
        const getKeySnapshot = (0, react_1.useCallback)((key) => {
          return key in state ? state[key] : void 0;
        }, [state]);
        const getServerSnapshot = (0, react_1.useCallback)((key) => {
          return key in initialState ? initialState[key] : void 0;
        }, [initialState]);
        const setState = (0, react_1.useCallback)((updater) => {
          setStateRaw(updater);
        }, []);
        (0, react_1.useEffect)(() => {
          const prev = prevStateRef.current;
          if (prev === state)
            return;
          prevStateRef.current = state;
          const seen = /* @__PURE__ */ new Set();
          const changedKeys = [];
          for (const k of Object.keys(prev)) {
            seen.add(k);
            if (prev[k] !== state[k])
              changedKeys.push(k);
          }
          for (const k of Object.keys(state)) {
            if (seen.has(k))
              continue;
            if (prev[k] !== state[k])
              changedKeys.push(k);
          }
          if (changedKeys.length === 0)
            return;
          changedKeys.forEach(notifyKey);
          if (debug) {
            console.log("[FusionState] State updated:", {
              previous: prev,
              next: state,
              diff: Object.fromEntries(changedKeys.map((k) => [k, state[k]]))
            });
          }
          if (devToolsInstance === null || devToolsInstance === void 0 ? void 0 : devToolsInstance.enabled) {
            devToolsInstance.send(devtools_1.DevToolsActions.SET_STATE, state, changedKeys.join(", "), {
              changed: changedKeys,
              diff: Object.fromEntries(changedKeys.map((k) => [k, { from: prev[k], to: state[k] }]))
            });
          }
          if (skipPersistOnceRef.current) {
            skipPersistOnceRef.current = false;
            return;
          }
          if (shouldSaveOnChange) {
            saveStateToStorage(state);
          }
        }, [
          state,
          notifyKey,
          debug,
          devToolsInstance,
          shouldSaveOnChange,
          saveStateToStorage
        ]);
        const value = (0, react_1.useMemo)(() => ({
          state,
          setState,
          initializingKeys: initializingKeys.current,
          subscribeKey,
          getKeySnapshot,
          getServerSnapshot,
          isHydrated
        }), [
          state,
          setState,
          subscribeKey,
          getKeySnapshot,
          getServerSnapshot,
          isHydrated
        ]);
        return react_1.default.createElement(GlobalStateContext.Provider, { value }, children);
      });
    }
  });

  // dist/createKey.js
  var require_createKey = __commonJS({
    "dist/createKey.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.UserKeys = exports.createNamespacedKey = exports.AppKeys = exports.extractKeyName = exports.isTypedKey = exports.createKey = void 0;
      function createKey(key) {
        return {
          __type: void 0,
          key,
          __brand: "FusionStateKey"
        };
      }
      exports.createKey = createKey;
      function isTypedKey(value) {
        return value && typeof value === "object" && value.__brand === "FusionStateKey" && typeof value.key === "string";
      }
      exports.isTypedKey = isTypedKey;
      function extractKeyName(keyOrString) {
        return isTypedKey(keyOrString) ? keyOrString.key : keyOrString;
      }
      exports.extractKeyName = extractKeyName;
      exports.AppKeys = {
        user: createKey("user"),
        cart: createKey("cart"),
        theme: createKey("theme"),
        settings: createKey("settings")
      };
      function createNamespacedKey(namespace, key) {
        return createKey(`${namespace}.${key}`);
      }
      exports.createNamespacedKey = createNamespacedKey;
      exports.UserKeys = {
        profile: createNamespacedKey("user", "profile"),
        preferences: createNamespacedKey("user", "preferences")
      };
    }
  });

  // dist/useFusionState.js
  var require_useFusionState = __commonJS({
    "dist/useFusionState.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.useFusionState = void 0;
      var react_1 = require_react();
      var FusionStateProvider_1 = require_FusionStateProvider();
      var types_1 = require_types();
      var utils_1 = require_utils();
      var createKey_1 = require_createKey();
      function useFusionState(keyInput, initialValue, options) {
        const key = (0, createKey_1.extractKeyName)(keyInput);
        const { state, setState, initializingKeys, subscribeKey, getKeySnapshot, getServerSnapshot } = (0, FusionStateProvider_1.useGlobalState)();
        const { shallow = false } = options || {};
        (0, react_1.useEffect)(() => {
          if (initialValue !== void 0 && !(key in state)) {
            if (initializingKeys.has(key)) {
              throw new Error((0, utils_1.formatErrorMessage)(types_1.FusionStateErrorMessages.KEY_ALREADY_INITIALIZING, key));
            }
            initializingKeys.add(key);
            try {
              setState((prev) => key in prev ? prev : Object.assign(Object.assign({}, prev), { [key]: initialValue }));
            } finally {
              initializingKeys.delete(key);
            }
          } else if (!(key in state) && initialValue === void 0) {
            throw new Error((0, utils_1.formatErrorMessage)(types_1.FusionStateErrorMessages.KEY_MISSING_NO_INITIAL, key));
          }
        }, [key, initialValue, state, initializingKeys, setState]);
        const currentValue = (0, react_1.useSyncExternalStore)((listener) => subscribeKey(key, listener), () => getKeySnapshot(key), getServerSnapshot ? () => getServerSnapshot(key) : () => initialValue);
        const setValue = (0, react_1.useCallback)((newValue) => {
          setState((prevState) => {
            const currentValue2 = prevState[key];
            const nextValue = typeof newValue === "function" ? newValue(currentValue2) : newValue;
            if (Object.is(currentValue2, nextValue)) {
              return prevState;
            }
            if (typeof nextValue === "object" && nextValue !== null && typeof currentValue2 === "object" && currentValue2 !== null) {
              const isEqual = shallow ? (0, utils_1.shallowEqual)(nextValue, currentValue2) : (0, utils_1.simpleDeepEqual)(nextValue, currentValue2);
              if (isEqual) {
                return prevState;
              }
            }
            return Object.assign(Object.assign({}, prevState), { [key]: nextValue });
          });
        }, [key, setState, shallow]);
        return [currentValue, setValue];
      }
      exports.useFusionState = useFusionState;
    }
  });

  // dist/useFusionStateLog.js
  var require_useFusionStateLog = __commonJS({
    "dist/useFusionStateLog.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.useFusionStateLog = void 0;
      var FusionStateProvider_1 = require_FusionStateProvider();
      var react_1 = require_react();
      var utils_1 = require_utils();
      var useFusionStateLog = (keys, options = {}) => {
        const { state } = (0, FusionStateProvider_1.useGlobalState)();
        const keysHash = (0, react_1.useMemo)(() => {
          if (!keys || keys.length === 0)
            return "";
          return `${keys.length}:${keys.join("")}`;
        }, [keys]);
        const filteredState = (0, react_1.useMemo)(() => {
          if (!keys || keys.length === 0) {
            return state;
          }
          const result = {};
          for (const key of keys) {
            if (key in state) {
              result[key] = state[key];
            }
          }
          return result;
        }, [state, keysHash]);
        const previousState = (0, react_1.useRef)({});
        const { trackChanges = false, changeDetection = "reference", formatter = void 0, consoleLog = false } = options;
        const compareValues = (0, react_1.useCallback)((a, b) => {
          return changeDetection === "reference" ? a === b : (0, utils_1.simpleDeepEqual)(a, b);
        }, [changeDetection]);
        (0, react_1.useEffect)(() => {
          let changes;
          if (trackChanges) {
            changes = {};
            for (const [key, value] of Object.entries(filteredState)) {
              const prevValue = previousState.current[key];
              if (!compareValues(value, prevValue)) {
                changes[key] = {
                  previous: prevValue,
                  current: value
                };
              }
            }
            if (Object.keys(changes).length === 0) {
              changes = void 0;
            }
          }
          previousState.current = Object.assign({}, filteredState);
          if (consoleLog && (changes || !trackChanges)) {
            const logData = formatter ? formatter(filteredState, changes) : Object.assign({ state: filteredState }, changes && { changes });
            console.log("[FusionState Log]", logData);
          }
        }, [filteredState, trackChanges, consoleLog, formatter, compareValues]);
        return filteredState;
      };
      exports.useFusionStateLog = useFusionStateLog;
    }
  });

  // dist/useFusionHydrated.js
  var require_useFusionHydrated = __commonJS({
    "dist/useFusionHydrated.js"(exports) {
      "use strict";
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.useFusionHydrated = void 0;
      var FusionStateProvider_1 = require_FusionStateProvider();
      function useFusionHydrated() {
        const { isHydrated } = (0, FusionStateProvider_1.useGlobalState)();
        return isHydrated !== null && isHydrated !== void 0 ? isHydrated : true;
      }
      exports.useFusionHydrated = useFusionHydrated;
    }
  });

  // dist/index.js
  var require_index = __commonJS({
    "dist/index.js"(exports) {
      Object.defineProperty(exports, "__esModule", { value: true });
      exports.autoDetectStorage = exports.createInMemoryAdapter = exports.createMobileStorageAdapter = exports.createRNStorageAdapter = exports.createWebStorageAdapter = exports.isSSREnvironment = exports.createMemoryStorageAdapter = exports.detectBestStorageAdapter = exports.NoopStorageAdapter = exports.createLocalStorageAdapter = exports.createNoopStorageAdapter = exports.simpleDeepEqual = exports.debounce = exports.formatErrorMessage = exports.PersistenceError = exports.FusionStateError = exports.FusionStateErrorMessages = exports.AppStateProvider = exports.StateProvider = exports.GlobalStateProvider = exports.useAppState = exports.usePersistentState = exports.useSharedState = exports.DevToolsActions = exports.useDevTools = exports.getDevTools = exports.createDevTools = exports.UserKeys = exports.AppKeys = exports.extractKeyName = exports.isTypedKey = exports.createNamespacedKey = exports.createKey = exports.useGlobalState = exports.useFusionHydrated = exports.useFusionStateLog = exports.createAsyncStorageAdapter = exports.FusionStateProvider = exports.useFusionState = void 0;
      var useFusionState_1 = require_useFusionState();
      Object.defineProperty(exports, "useFusionState", { enumerable: true, get: function() {
        return useFusionState_1.useFusionState;
      } });
      var FusionStateProvider_1 = require_FusionStateProvider();
      Object.defineProperty(exports, "FusionStateProvider", { enumerable: true, get: function() {
        return FusionStateProvider_1.FusionStateProvider;
      } });
      var asyncStorageAdapter_1 = require_asyncStorageAdapter();
      Object.defineProperty(exports, "createAsyncStorageAdapter", { enumerable: true, get: function() {
        return asyncStorageAdapter_1.createAsyncStorageAdapter;
      } });
      var useFusionStateLog_1 = require_useFusionStateLog();
      Object.defineProperty(exports, "useFusionStateLog", { enumerable: true, get: function() {
        return useFusionStateLog_1.useFusionStateLog;
      } });
      var useFusionHydrated_1 = require_useFusionHydrated();
      Object.defineProperty(exports, "useFusionHydrated", { enumerable: true, get: function() {
        return useFusionHydrated_1.useFusionHydrated;
      } });
      var FusionStateProvider_2 = require_FusionStateProvider();
      Object.defineProperty(exports, "useGlobalState", { enumerable: true, get: function() {
        return FusionStateProvider_2.useGlobalState;
      } });
      var createKey_1 = require_createKey();
      Object.defineProperty(exports, "createKey", { enumerable: true, get: function() {
        return createKey_1.createKey;
      } });
      Object.defineProperty(exports, "createNamespacedKey", { enumerable: true, get: function() {
        return createKey_1.createNamespacedKey;
      } });
      Object.defineProperty(exports, "isTypedKey", { enumerable: true, get: function() {
        return createKey_1.isTypedKey;
      } });
      Object.defineProperty(exports, "extractKeyName", { enumerable: true, get: function() {
        return createKey_1.extractKeyName;
      } });
      Object.defineProperty(exports, "AppKeys", { enumerable: true, get: function() {
        return createKey_1.AppKeys;
      } });
      Object.defineProperty(exports, "UserKeys", { enumerable: true, get: function() {
        return createKey_1.UserKeys;
      } });
      var devtools_1 = require_devtools();
      Object.defineProperty(exports, "createDevTools", { enumerable: true, get: function() {
        return devtools_1.createDevTools;
      } });
      Object.defineProperty(exports, "getDevTools", { enumerable: true, get: function() {
        return devtools_1.getDevTools;
      } });
      Object.defineProperty(exports, "useDevTools", { enumerable: true, get: function() {
        return devtools_1.useDevTools;
      } });
      Object.defineProperty(exports, "DevToolsActions", { enumerable: true, get: function() {
        return devtools_1.DevToolsActions;
      } });
      exports.useSharedState = useFusionState_1.useFusionState;
      exports.usePersistentState = useFusionState_1.useFusionState;
      exports.useAppState = useFusionState_1.useFusionState;
      exports.GlobalStateProvider = FusionStateProvider_1.FusionStateProvider;
      exports.StateProvider = FusionStateProvider_1.FusionStateProvider;
      exports.AppStateProvider = FusionStateProvider_1.FusionStateProvider;
      var types_1 = require_types();
      Object.defineProperty(exports, "FusionStateErrorMessages", { enumerable: true, get: function() {
        return types_1.FusionStateErrorMessages;
      } });
      Object.defineProperty(exports, "FusionStateError", { enumerable: true, get: function() {
        return types_1.FusionStateError;
      } });
      Object.defineProperty(exports, "PersistenceError", { enumerable: true, get: function() {
        return types_1.PersistenceError;
      } });
      var utils_1 = require_utils();
      Object.defineProperty(exports, "formatErrorMessage", { enumerable: true, get: function() {
        return utils_1.formatErrorMessage;
      } });
      Object.defineProperty(exports, "debounce", { enumerable: true, get: function() {
        return utils_1.debounce;
      } });
      Object.defineProperty(exports, "simpleDeepEqual", { enumerable: true, get: function() {
        return utils_1.simpleDeepEqual;
      } });
      var storageAdapters_1 = require_storageAdapters();
      var autoDetect_1 = require_autoDetect();
      var storageAdapters_2 = require_storageAdapters();
      Object.defineProperty(exports, "createNoopStorageAdapter", { enumerable: true, get: function() {
        return storageAdapters_2.createNoopStorageAdapter;
      } });
      Object.defineProperty(exports, "createLocalStorageAdapter", { enumerable: true, get: function() {
        return storageAdapters_2.createLocalStorageAdapter;
      } });
      Object.defineProperty(exports, "NoopStorageAdapter", { enumerable: true, get: function() {
        return storageAdapters_2.NoopStorageAdapter;
      } });
      var autoDetect_2 = require_autoDetect();
      Object.defineProperty(exports, "detectBestStorageAdapter", { enumerable: true, get: function() {
        return autoDetect_2.detectBestStorageAdapter;
      } });
      Object.defineProperty(exports, "createMemoryStorageAdapter", { enumerable: true, get: function() {
        return autoDetect_2.createMemoryStorageAdapter;
      } });
      Object.defineProperty(exports, "isSSREnvironment", { enumerable: true, get: function() {
        return autoDetect_2.isSSREnvironment;
      } });
      exports.createWebStorageAdapter = storageAdapters_1.createLocalStorageAdapter;
      exports.createRNStorageAdapter = asyncStorageAdapter_1.createAsyncStorageAdapter;
      exports.createMobileStorageAdapter = asyncStorageAdapter_1.createAsyncStorageAdapter;
      exports.createInMemoryAdapter = autoDetect_1.createMemoryStorageAdapter;
      exports.autoDetectStorage = autoDetect_1.detectBestStorageAdapter;
    }
  });
  return require_index();
})();
ReactFusionState.VERSION = "1.1.1";
